name: Build and Release

on:
  release:
    types: [created, published, edited, deleted, prereleased, unpublished]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: clang
          - os: windows-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: gcc

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }} -DCMAKE_CXX_FLAGS_RELEASE="-O3"

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Package
      env:
        VERSION: ${{ github.event.release.tag_name }}
        OS: ${{ matrix.os }}
      run: |
        zip -r aq-$VERSION-$OS.zip build/*
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: aq-${{ github.event.release.tag_name }}-${{ matrix.os }}.zip
        path: aq-${{ github.event.release.tag_name }}-${{ matrix.os }}.zip
