name: Build and Release

on:
  release:
    types: [created, updated]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86, x64, arm64]
        include:
          - os: ubuntu-latest
            arch: x86
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            arch: x64
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            arch: arm64
            c_compiler: gcc
            cpp_compiler: g++
          - os: windows-latest
            arch: x86
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            arch: x64
            c_compiler: cl
            cpp_compiler: cl
          - os: windows-latest
            arch: arm64
            c_compiler: cl
            cpp_compiler: cl
          - os: macos-latest
            arch: x86
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            arch: x64
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            arch: arm64
            c_compiler: clang
            cpp_compiler: clang++

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} -DCMAKE_BUILD_TYPE=Release -S ${{ github.workspace }} -DCMAKE_CXX_FLAGS_RELEASE="-O3"

    - name: Build
      run: cmake --build build --config Release

    - name: Download Source Code
      run: |
        git clone --depth 1 https://github.com/aq-org/AQ.git build

    - name: Upload artifact (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v3
      with:
        name: aq-${{ github.event.release.tag_name }}-linux-${{ matrix.arch }}
        path: build/*

    - name: Upload artifact (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v3
      with:
        name: aq-${{ github.event.release.tag_name }}-windows-${{ matrix.arch }}
        path: build/*

    - name: Upload artifact (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v3
      with:
        name: aq-${{ github.event.release.tag_name }}-macos-${{ matrix.arch }}
        path: build/*

    - name: Compress Release Asset (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        zip -r aq-${{ github.event.release.tag_name }}-linux-${{ matrix.arch }}.zip build

    - name: Compress Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        powershell Compress-Archive -Path build\* -DestinationPath aq-${{ github.event.release.tag_name }}-windows-${{ matrix.arch }}.zip

    - name: Compress Release Asset (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        zip -r aq-${{ github.event.release.tag_name }}-macos-${{ matrix.arch }}.zip build

    - name: Upload Release Asset (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: aq-${{ github.event.release.tag_name }}-linux-${{ matrix.arch }}.zip
        asset_name: aq-${{ github.event.release.tag_name }}-linux-${{ matrix.arch }}.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Windows)
      if: matrix.os == 'windows-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: aq-${{ github.event.release.tag_name }}-windows-${{ matrix.arch }}.zip
        asset_name: aq-${{ github.event.release.tag_name }}-windows-${{ matrix.arch }}.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (macOS)
      if: matrix.os == 'macos-latest'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: aq-${{ github.event.release.tag_name }}-macos-${{ matrix.arch }}.zip
        asset_name: aq-${{ github.event.release.tag_name }}-macos-${{ matrix.arch }}.zip
        asset_content_type: application/zip
